import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fundamentals Ape</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="monkey.png" />
      </Head>

      <div className={styles.bodyContainer}>
        <div>
        <img src="monkey2.png" className={styles.monkeyLogo} />
        </div>
        <div>
          <h1 className={styles.siteTitle}>Fundamentals Ape</h1>
        </div>
        <div className={styles.subtitleContainer}>
          <Link href='/posts'>
            <a>
            <text className={styles.subtitleText}>
              Blog
            </text>
            </a>
          </Link>
          <Link href='/About'>
            <a>
            <text className={styles.subtitleText}>
              About Me
            </text>
            </a>
          </Link>
        </div>
      </div>
    </div>
  )
}
